# PLACEHOLDER — generated by nixos-anywhere --generate-hardware-config nixos-facter
# on the first deploy. This file is committed so subsequent rebuilds don't
# need to re-run facter. The first nixos-anywhere run will OVERWRITE this file.
{ ... }:
{
  boot.initrd.availableKernelModules = [ "virtio_pci" "virtio_blk" "virtio_scsi" "virtio_net" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  swapDevices = [ ];
  networking.useDHCP = true;
}
