# PLACEHOLDER — generated by nixos-anywhere --generate-hardware-config nixos-facter
# on the first deploy. This file is committed so subsequent rebuilds don't
# need to re-run facter. The first nixos-anywhere run will OVERWRITE this file.
{ ... }:
{
  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  swapDevices = [ ];
  networking.useDHCP = true;
}
