{ den, inputs, lib, pkgs, ... }:

{
  den.aspects.server.rusty-imap = {
    nixos = { config, lib, pkgs, ... }:
    let
      # Safely access sops paths — sops module may not be loaded yet
      emailAdressPath = lib.attrByPath [ "sops" "secrets" "email/gmail/account1/adress" "path" ] null config;
    in {
      # System user that owns secrets + runs the service
      users.users.rusty-imap = {
        isSystemUser = true;
        group = "rusty-imap";
        home = "/var/lib/rusty-imap";
        createHome = true;
        extraGroups = [ "hermes" ];
      };
      users.groups.rusty-imap = {};

      # Generate config.toml with email address from sops
      system.activationScripts.rusty-imap-config = lib.stringAfter ([ "var" ] ++ lib.optional (config.system.activationScripts ? sops) "sops") ''
        ${lib.optionalString (emailAdressPath != null) ''
          EMAIL_ADDR=$(cat ${emailAdressPath} 2>/dev/null || echo "")

          if [ -n "$EMAIL_ADDR" ]; then
            mkdir -p /var/lib/hermes/rusty-imap
            cat > /var/lib/hermes/rusty-imap/config.toml << CONFIG_EOF
# rusty-imap-mcp config for Gmail — PII-redacting fork
# Generated by NixOS — DO NOT EDIT

[imap]
host = "imap.gmail.com"
port = 993
username = "$EMAIL_ADDR"
# Password resolved from env RUSTY_IMAP_MCP_IMAP_PASSWORD at startup

[security]
posture = "draft-safe"

[security.tools]
"search.advanced_query" = "allow"

[audit]
# Disabled — each child process needs a unique path, but hyper-mcp-proxy
# spawns per-session children from the same config
enabled = false

[attachments]
download_dir = "/var/lib/rusty-imap/.local/share/rusty-imap-mcp/attachments"
CONFIG_EOF
            mkdir -p /var/lib/rusty-imap/.local/share/rusty-imap-mcp/attachments
            chown -R rusty-imap:rusty-imap /var/lib/rusty-imap/.local
            chmod 600 /var/lib/hermes/rusty-imap/config.toml
          fi
        ''}
      '';

      # Ensure directories exist
      systemd.tmpfiles.rules = [
        "d /var/lib/rusty-imap/.local/share/rusty-imap-mcp 0755 rusty-imap rusty-imap -"
        "d /var/lib/rusty-imap/.local/share/rusty-imap-mcp/attachments 0755 rusty-imap rusty-imap -"
      ];

      # Systemd service: hyper-mcp-proxy → rusty-imap-mcp
      systemd.services.rusty-imap-mcp = {
        description = "MCP email proxy — hyper-mcp-proxy → rusty-imap-mcp";
        after = [ "network-online.target" "sops-nix.service" ];
        wants = [ "network-online.target" ];
        wantedBy = [ "multi-user.target" ];

        serviceConfig = {
          User = "rusty-imap";
          Group = "rusty-imap";
          Restart = "on-failure";
          RestartSec = 5;
        };

        script = ''
          export RUSTY_IMAP_MCP_IMAP_PASSWORD=$(cat /run/secrets/email/gmail/account1/app-password)

          exec /var/lib/hermes/.local/bin/hyper-mcp-proxy \
            -p 6789 \
            -- /var/lib/hermes/.local/bin/rusty-imap-mcp \
            --config /var/lib/hermes/rusty-imap/config.toml
        '';
      };
    };
  };
}