services:
  caddy:
    ports:
      - "8080:80"
      - "8444:443"
  postgres:
    volumes:
      - /opt/evc-team-relay/data/postgres:/var/lib/postgresql/data
  minio:
    volumes:
      - /tank/evc-team-relay/minio:/data
  control-plane:
    volumes:
      - /tank/evc-team-relay/uploads:/app/app/static/uploads
  postgres-backup:
    volumes:
      - /tank/evc-team-relay/backups:/backups
  relay-server:
    volumes:
      - /tank/evc-team-relay/relay:/app/data
      - ./relay/relay.toml:/app/relay.toml:ro
